remote_theme: just-the-docs/just-the-docs@v0.10.2

title: Evolve Plus for Sailfish OS
description: Evolve Plus for Sailfish OS

url: "https://uithemer.github.io"
baseurl: "/harbour-themepack-evolve-plus"
repository: uithemer/harbour-themepack-evolve-plus

search_enabled: false

aux_links:
  "Evolve Plus on GitHub":
    - "https://github.com/uithemer/harbour-themepack-evolve-plus"

exclude:
  - appicons/
  - other/
  - qml/
  - rpm/
  - src/
  - theme/
  - translations/
  - .sfdk/
  - RPMS/
  - LICENSE
  - "*.desktop"
  - "*.pro"
  - "*.pro.user"
  - .gitignore
  - .jekyll-cache/
  - vendor/
